使用率“
WSJ20@LAPTOP-PTA5LSR2 MINGW64 ~
$ git config --global user.name Catherinesj

WSJ20@LAPTOP-PTA5LSR2 MINGW64 ~
$ git config --global user.name 1754553490@qq.com

WSJ20@LAPTOP-PTA5LSR2 MINGW64 ~
$ git config --global user.name Catherinesj

WSJ20@LAPTOP-PTA5LSR2 MINGW64 ~
$ git config --global user.email Catherinesj

WSJ20@LAPTOP-PTA5LSR2 MINGW64 ~
$ cd ~/.ssh

WSJ20@LAPTOP-PTA5LSR2 MINGW64 ~/.ssh
$ ls
config  known_hosts

WSJ20@LAPTOP-PTA5LSR2 MINGW64 ~/.ssh
$ ^C

WSJ20@LAPTOP-PTA5LSR2 MINGW64 ~/.ssh
$ git config --global --list
user.name=Catherinesj
user.email=Catherinesj
email.name=1754553490@qq.com
credential.helper=store

WSJ20@LAPTOP-PTA5LSR2 MINGW64 ~/.ssh
$ ^C

WSJ20@LAPTOP-PTA5LSR2 MINGW64 ~/.ssh
$ # 删除全局的 user.email 配置
git config --global --unset user.email

WSJ20@LAPTOP-PTA5LSR2 MINGW64 ~/.ssh
$ git config --global --list
user.name=Catherinesj
email.name=1754553490@qq.com
credential.helper=store

WSJ20@LAPTOP-PTA5LSR2 MINGW64 ~/.ssh
$ git config --global --unset email.name

WSJ20@LAPTOP-PTA5LSR2 MINGW64 ~/.ssh
$ git config --global --list
user.name=Catherinesj
credential.helper=store

WSJ20@LAPTOP-PTA5LSR2 MINGW64 ~/.ssh
$ git config --global user.email 1754553490@qq.com

WSJ20@LAPTOP-PTA5LSR2 MINGW64 ~/.ssh
$ git config --global --list
user.name=Catherinesj
user.email=1754553490@qq.com
credential.helper=store

WSJ20@LAPTOP-PTA5LSR2 MINGW64 ~/.ssh
$ ls
config  known_hosts

WSJ20@LAPTOP-PTA5LSR2 MINGW64 ~/.ssh
$ ^C

WSJ20@LAPTOP-PTA5LSR2 MINGW64 ~/.ssh
$ ssh-keygen -t rsa -b 4096 -C 1754553490@qq.com
Generating public/private rsa key pair.
Enter file in which to save the key (/c/Users/WSJ20/.ssh/id_rsa):
Enter passphrase for /c/Users/WSJ20/.ssh/id_rsa (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /c/Users/WSJ20/.ssh/id_rsa
Your public key has been saved in /c/Users/WSJ20/.ssh/id_rsa.pub
The key fingerprint is:
SHA256:a0nBXmuE6a/KTPiq7eWmaL6oOp5hw+xq/ziuKbp04kw 1754553490@qq.com
The key's randomart image is:
+---[RSA 4096]----+
|                 |
|       . o       |
|        = o      |
|       o + .     |
|        S o      |
|o    . . =       |
| E .. o + .      |
|XoO+.B.. .       |
|/&OBB=*..        |
+----[SHA256]-----+

WSJ20@LAPTOP-PTA5LSR2 MINGW64 ~/.ssh
$ ls
config  id_rsa  id_rsa.pub  known_hosts

WSJ20@LAPTOP-PTA5LSR2 MINGW64 ~/.ssh
$ cd d:

WSJ20@LAPTOP-PTA5LSR2 MINGW64 /d
$ ls
'.BIN'/                carmera_sdk/
'.~TMP'/               chengxu/
 ABAQUS/                       clashcn.com_Clash.for.Windows-0.20.39-win-CN/
 Android/                      clion/
 BaiduNetdiskDownload/         cxdownload/
 CAD/                          c语言/
 Config.Msi/                   git/
 DTLFolder/                    imager/
 Desktop/                      iodraw/
 Downloads/                    j_link_download/
 DumpStack.log.tmp             matlab/
'Huawei Share'/                mingw64/
 JetBrains-2025-po-jie-bao/    opencv_C++/
 K210/                         origin/
 K230/                         pagefile.sys
 KSWJJ/                        proteus/
 KuGou/                        python-learn/
 Parblo/                       quark-cloud-drive/
'Program Files'/               qudongrensheng/
'Program Files (x86)'/         resa_uart/
 ProgramData/                  solidworks2023/
 QQMusicCache/                 todesk/
 QQ文件/                       ultralytics/
 RA/                           vmware/
 Raspberry/                    vs/
 SIMULIA/                      win32diskimager/
 Simula_License_Server/        xiangrikui/
'System Volume Information'/   xiaogongju/
'Ubuntu 64 位.vmx.lck'/        yolo/
 Ubuntu-20/                    yunleiyunpan/
 VNC/                         '~$主控板.SLDASM'
'Windows Kits'/                共享文件夹/
 WindowsApps/                  办公重要/
'Witmotion(V2025.7.28.0)'/     华为云盘/
 WpSystem/                     安装文件夹/
 Zotero/                       聊天文件/
 anaconda/                     迅雷下载/
 balenaEtcher/                 迅雷云盘/
 bambu/

WSJ20@LAPTOP-PTA5LSR2 MINGW64 /d
$ cd Desktop/

WSJ20@LAPTOP-PTA5LSR2 MINGW64 /d/Desktop
$ ls
'Abaqus CAE.lnk'*
'AutoCAD 2022 - 简体中文 (Simplified Chinese).lnk'*
'CanMV IDE.lnk'*
'Docker Desktop.lnk'*
'Keil uVision5.LNK'*
'Origin 2025b.lnk'*
'Proteus 8 Professional.lnk'*
 QQ浏览器.lnk*
'Renesas RA Smart Configurator 4.4.0.lnk'*
'UartAssist.exe - 快捷方式.lnk'*
 VideoCap.exe*
'Visual Studio Code.lnk'*
 desktop.ini
'e2studio.exe - 快捷方式.lnk'*

Aborting commit due to empty commit message.

WSJ20@LAPTOP-PTA5LSR2 MINGW64 /d/Desktop/协会 (master)
$ git remote add origin git@github.com:Catherinesj/daily_code.git

WSJ20@LAPTOP-PTA5LSR2 MINGW64 /d/Desktop/协会 (master)
$ git push -u origin master
error: src refspec master does not match any
error: failed to push some refs to 'github.com:Catherinesj/daily_code.git'

WSJ20@LAPTOP-PTA5LSR2 MINGW64 /d/Desktop/协会 (master)
$ ^C

WSJ20@LAPTOP-PTA5LSR2 MINGW64 /d/Desktop/协会 (master)
$ git add .

WSJ20@LAPTOP-PTA5LSR2 MINGW64 /d/Desktop/协会 (master)
$ git commit -m使用率“